### ISSUE TITLE
Weird reboot after STOP problems

### ISSUE THREAD

**Issue by yqxq** [p2000t/M2000#132] opened 2024-03-20 11:04 UTC
M2000 behaves different than a real machine after STOP.
Some programs get into a reload/reboot loop and can't be quit, where this is possible on real hardware. For example with the Cassette Kopieerhulp program.
Maybe it is nice to include a "Open MCDR" toggle in the menu, so you can leave the tape loaded, but put the door open virtually. It would greatly increase usability.

**Comment by dionoid** [comment] 2024-03-27 21:18
There are several 'Cassette Kopieerhulp' programs, so can you send me the specific program which has the issue? And which OS and version of M2000 are you running? Can you describe the reproduction-steps and what you observed and what was expected? And with STOP, are you referring to the STOP-key or the STOP basic command?

**Comment by yqxq** [comment] 2024-04-23 09:52
Het gaat om KOPIE MAKEN van Hans Pennings (v 3.0). 
[90 Cassette Kopieerprogramma.zip](https://github.com/p2000t/M2000/files/15138173/90.Cassette.Kopieerprogramma.zip)

**Comment by dionoid** [comment] 2024-04-27 14:51
I don't think this is a bug, as the program you've sent me seems to be an alternative version of "KOPIE MAKEN", which after STOP will load and run the first program from tape again. The version I have actually stops after you press the STOP key, see [Kopie Maken.zip](https://github.com/p2000t/M2000/files/15138510/Kopie.Maken.zip)

Below you see the Basic code of your version of "KOPIE MAKEN" vs. my version. Notice that your version has `RUN"` as last instruction on line 1, which basically just restarts the program:

![image](https://github.com/p2000t/M2000/assets/3540187/8de40cc5-5784-4fa6-8fd4-1b8317395ac8)

**Comment by dionoid** [comment] 2024-05-03 14:56
Works like intended. Closing this issue.

**Closed as completed by dionoid** 2024-05-03 14:56 UTC
Labels: wontfix, Needs more information, works like intended
